### ISSUE TITLE
about installation packages

### ISSUE THREAD

**Issue by John122-art** [xichennn/V2X_traj_prediction#2]
Thank you for your work. I have been following it for a long time and find it innovative and successful. I would like to learn from it. Could you please share information regarding the versions of the installation packages and the data preprocessing process? I would greatly appreciate it if you could do so!

**Comment by xichennn** [comment]
Hi, Thanks for the kind words. Please follow https://github.com/xichennn/MSMA for modeling package installation. For the conformal prediction part, please follow the instructions here:https://github.com/Rose-STL-Lab/CopulaCPTS. Good luck!

**Comment by John122-art** [comment]
thanks!
________________________________
发件人: Xi Chen, PhD ***@***.***>
发送时间: 2024年9月18日 21:32
收件人: xichennn/V2I_trajectory_prediction ***@***.***>
抄送: Linqingh ***@***.***>; Author ***@***.***>
主题: Re: [xichennn/V2I_trajectory_prediction] about installation packages (Issue #2)


Hi, Thanks for the kind words. Please follow https://github.com/xichennn/MSMA for modeling package installation. For the conformal prediction part, please follow the instructions here:https://github.com/Rose-STL-Lab/CopulaCPTS. Good luck!

―
