### ISSUE TITLE
Can not reproduce results in the V2INet report

### ISSUE THREAD

**Issue by hshaoh** [xichennn/V2X_traj_prediction#3]
Thank you for your wonderful work. We tried to train V2INet.  However, I could not manage to reproduce the reported metrics.

**Comment by John122-art** [comment]
> Thank you for your wonderful work. We tried to train V2INet. However, I could not manage to reproduce the reported metrics.
你好，我刚刚入门V2X，在复现这篇论文的时候遇到了一些问题，请教您一下：
1.您在复现本论文时，用的V2X-seq-TFD还是V2X-seq-TFD-Example?
2.我用的V2X-seq-TFD-Example，在dair_map_api.py中处理地图json文件时候出现了错误：Seed set to 2024
Processing...
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    datamodule.setup()
  File "/media/V2I_main/datamodules/v2x_datamodule.py", line 37, in setup
    self.val_dataset = V2XDataset(self.root, 'val', self.val_transform, self.local_radius)
  File "/media/V2I_main/datasets/v2x_dataset.py", line 42, in __init__
    super(V2XDataset, self).__init__(root=root, transform=transform)
  File "/root/miniconda3/envs/cop/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 115, in __init__
    self._process()
  File "/root/miniconda3/envs/cop/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 262, in _process
    self.process()
  File "/media/V2I_main/datasets/v2x_dataset.py", line 88, in process
    dm = DAIRV2XMap()
  File "/media/V2I_main/datasets/dair_map_api.py", line 63, in __init__
    ) = self.build_hallucinated_lane_bbox_index()
  File "/media/V2I_main/datasets/dair_map_api.py", line 178, in build_hallucinated_lane_bbox_index
    city_halluc_tableidx_to_laneid_map[city_name] = read_json_file(json_fpath)
  File "/media/V2I_main/API/argoverse/utils/json_utils.py", line 18, in read_json_file
    with open(fpath, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/V2X-Seq-data/maps/yizhuang_PEK_tableidx_to_laneid_map.json'
如果您能解答，万分感激！

**Comment by hshaoh** [comment]
> > Thank you for your wonderful work. We tried to train V2INet. However, I could not manage to reproduce the reported metrics.
> > 你好，我刚刚入门V2X，在复现这篇论文的时候遇到了一些问题，请教您一下：
> > 1.您在复现本论文时，用的V2X-seq-TFD还是V2X-seq-TFD-Example?
> > 2.我用的V2X-seq-TFD-Example，在dair_map_api.py中处理地图json文件时候出现了错误：Seed set to 2024
> > Processing...
> > Traceback (most recent call last):
> > File "train.py", line 41, in 
> > datamodule.setup()
> > File "/media/V2I_main/datamodules/v2x_datamodule.py", line 37, in setup
> > self.val_dataset = V2XDataset(self.root, 'val', self.val_transform, self.local_radius)
> > File "/media/V2I_main/datasets/v2x_dataset.py", line 42, in **init**
> > super(V2XDataset, self).**init**(root=root, transform=transform)
> > File "/root/miniconda3/envs/cop/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 115, in **init**
> > self._process()
> > File "/root/miniconda3/envs/cop/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 262, in _process
> > self.process()
> > File "/media/V2I_main/datasets/v2x_dataset.py", line 88, in process
> > dm = DAIRV2XMap()
> > File "/media/V2I_main/datasets/dair_map_api.py", line 63, in **init**
> > ) = self.build_hallucinated_lane_bbox_index()
> > File "/media/V2I_main/datasets/dair_map_api.py", line 178, in build_hallucinated_lane_bbox_index
> > city_halluc_tableidx_to_laneid_map[city_name] = read_json_file(json_fpath)
> > File "/media/V2I_main/API/argoverse/utils/json_utils.py", line 18, in read_json_file
> > with open(fpath, "rb") as f:
> > FileNotFoundError: [Errno 2] No such file or directory: '/media/V2X-Seq-data/maps/yizhuang_PEK_tableidx_to_laneid_map.json'
> > 如果您能解答，万分感激！

也许你需要使用官方提供的合并工具将28张高清地图合并到一张地图中，得到map_files文件夹，具体教程网址https://github.com/AIR-THU/DAIR-V2X-Seq/blob/main/docs/apis/map_loader.md，其中有你需要的media/V2X-Seq-data/maps/yizhuang_PEK_tableidx_to_laneid_map.json'

**Comment by John122-art** [comment]
感谢您的回复！！我已经解决了上述问题，现在在解决数据预处理问题，请问一下我是不是应该按照https://github.com/AIR-THU/DAIR-V2X-Seq/tree/main/docs/benchmarks/vic-traj-forecasting/HiVT 中的方法进行数据预处理和训练？
![111](https://github.com/user-attachments/assets/89e816c5-1749-4145-b738-5ebf5a4bb407)
![222](https://github.com/user-attachments/assets/3a9ce557-abb9-4fdf-9339-3113d6d5640e)

**Comment by xichennn** [comment]
Hi, reproducing metrics can be challenging without an identical environment. I faced the same issue with V2X-Seq—while I couldn't fully replicate the results, I managed to get reasonably close. what's your number like?

**Comment by Aurora-arrive** [comment]
> Hi, reproducing metrics can be challenging without an identical environment. I faced the same issue with V2X-Seq—while I couldn't fully replicate the results, I managed to get reasonably close. what's your number like?

I trained on a sheet of 3090s and got the following metrics on the validation set. I'm not sure what I did wrong at that step
![image](https://github.com/user-attachments/assets/8b3f1176-0dc0-466a-b00c-294cc397f6cb)

**Comment by Aurora-arrive** [comment]
> > Hi, reproducing metrics can be challenging without an identical environment. I faced the same issue with V2X-Seq—while I couldn't fully replicate the results, I managed to get reasonably close. what's your number like?
> 
> Hi, thanks for the reply. I trained on a sheet of 3090s and got the following metrics on the validation set. I'm not sure what I did wrong at that step ![image](https://private-user-images.githubusercontent.com/89620683/393136519-8b3f1176-0dc0-466a-b00c-294cc397f6cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Njk5NDQsIm5iZiI6MTczMzQ2OTY0NCwicGF0aCI6Ii84OTYyMDY4My8zOTMxMzY1MTktOGIzZjExNzYtMGRjMC00NjZhLWIwMGMtMjk0Y2MzOTdmNmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA3MjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3N2E5ZjkyZjA1MjU1Y2I3NDc1NDAzMzE2OTM2NDNkZDViMTc0YjkzOTYwZmY2NjdmYjZhZmYxZjYzMGUxYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5DKULsa6lzpOCgN4Ce01-1EVurU3Vn0_nj6ciDEwuLw) I wonder if it would be convenient for you to send me the checkpoint file to my email（[heshaohui@bupt.edu.cn](mailto:heshaohui@bupt.edu.cn)）. Thank you for your kind help.
